import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("lp", "routes/lp.tsx"),
  route("lp/ja", "routes/lp.tsx", { id: "lp-ja" }),
  route("terms", "routes/terms.tsx"),
  route("terms/ja", "routes/terms.tsx", { id: "terms-ja" }),
  route("policy", "routes/policy.tsx"),
  route("policy/ja", "routes/policy.tsx", { id: "policy-ja" }),
  route("manual/:chapter?", "routes/manual.tsx"),
  route("manual/ja/:chapter?", "routes/manual.tsx", { id: "manual-ja" }),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/unlock", "routes/api.auth.unlock.tsx"),
  route("settings", "routes/settings.tsx"),
  // API routes
  route("api/drive/files", "routes/api.drive.files.tsx"),
  route("api/drive/tree", "routes/api.drive.tree.tsx"),
  route("api/workflow/execute-node", "routes/api.workflow.execute-node.tsx"),
  route("api/workflow/mcp-proxy", "routes/api.workflow.mcp-proxy.tsx"),
  route("api/workflow/http-fetch", "routes/api.workflow.http-fetch.tsx"),
  route("api/workflow/ai-generate", "routes/api.workflow.ai-generate.tsx"),
  route("api/workflow/ai-prompt", "routes/api.workflow.ai-prompt.tsx"),
  route("api/workflow/history", "routes/api.workflow.history.tsx"),
  route("api/workflow/request-history", "routes/api.workflow.request-history.tsx"),
  route("api/chat", "routes/api.chat.tsx"),
  route("api/chat/interactions", "routes/api.chat.interactions.tsx"),
  route("api/chat/compact", "routes/api.chat.compact.tsx"),
  route("api/chat/history", "routes/api.chat.history.tsx"),
  route("api/settings/mcp-test", "routes/api.settings.mcp-test.tsx"),
  route("api/settings/mcp-oauth-token", "routes/api.settings.mcp-oauth-token.tsx"),
  route("auth/mcp-oauth-callback", "routes/auth.mcp-oauth-callback.tsx"),
  route("api/settings/rag-sync", "routes/api.settings.rag-sync.tsx"),
  route("api/settings/encryption", "routes/api.settings.encryption.tsx"),
  route("api/settings/edit-history", "routes/api.settings.edit-history.tsx"),
  route("api/settings/edit-history-stats", "routes/api.settings.edit-history-stats.tsx"),
  route("api/settings/edit-history-prune", "routes/api.settings.edit-history-prune.tsx"),
  route("api/settings/hubwork-sheets", "routes/api.settings.hubwork-sheets.tsx"),
  route("api/settings/hubwork-provision", "routes/api.settings.hubwork-provision.tsx"),
  route("api/settings/hubwork-migrate", "routes/api.settings.hubwork-migrate.tsx"),
  route("api/calendar", "routes/api.calendar.tsx"),
  route("api/gmail", "routes/api.gmail.tsx"),
  route("api/sheets", "routes/api.sheets.tsx"),
  route("api/mcp/tool-call", "routes/api.mcp.tool-call.tsx"),
  route("api/mcp/resource-read", "routes/api.mcp.resource-read.tsx"),
  route("api/search", "routes/api.search.tsx"),
  route("api/sync", "routes/api.sync.tsx"),
  route("api/drive/upload", "routes/api.drive.upload.tsx"),
  route("api/drive/temp", "routes/api.drive.temp.tsx"),
  // Public (no auth) — temp edit URLs for local editor integration
  route("api/temp-edit/:token/:fileName", "routes/api.temp-edit.$token.$fileName.tsx"),
  // Public (no auth) — serves published Drive files with correct Content-Type
  route("public/file/:fileId/:fileName", "routes/public.file.$fileId.$fileName.tsx"),
  route("api/plugins", "routes/api.plugins.tsx"),
  route("api/plugins/:id", "routes/api.plugins.$id.tsx"),
  route("api/obsidian/token", "routes/api.obsidian.token.tsx"),
  // Hubwork routes
  route("hubwork/api/domain", "routes/hubwork.api.domain.tsx"),
  // Hubwork internal endpoints (/__gemihub/ prefix)
  route("__gemihub/auth/login", "routes/hubwork.internal.auth.login.tsx"),
  route("__gemihub/auth/verify/:token", "routes/hubwork.internal.auth.verify.$token.tsx"),
  route("__gemihub/auth/logout", "routes/hubwork.internal.auth.logout.tsx"),
  route("__gemihub/auth/me", "routes/hubwork.internal.auth.me.tsx"),
  route("__gemihub/api.js", "routes/hubwork.internal.api-js.tsx"),
  route("__gemihub/api/*", "routes/hubwork.internal.api.$.tsx"),
  route("api/workflow/execute-full", "routes/api.workflow.execute-full.tsx"),
  route("hubwork/api/workflow/scheduled", "routes/hubwork.api.workflow.scheduled.tsx"),
  // Hubwork admin
  route("hubwork/admin", "routes/hubwork.admin.tsx"),
  route("hubwork/admin/accounts/:accountId", "routes/hubwork.admin.account.tsx"),
  route("hubwork/admin/accounts/create", "routes/hubwork.admin.account-create.tsx"),
  // Hubwork Stripe
  route("hubwork/api/stripe/checkout", "routes/hubwork.api.stripe.checkout.tsx"),
  route("hubwork/api/stripe/webhook", "routes/hubwork.api.stripe.webhook.tsx"),
  route("hubwork/api/stripe/portal", "routes/hubwork.api.stripe.portal.tsx"),
  // Hubwork site catch-all (must be last — serves pages from Drive on Hubwork domains)
  route("*", "routes/hubwork.site.$.tsx"),
] satisfies RouteConfig;
