import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("lp", "routes/lp.tsx"),
  route("lp/ja", "routes/lp.tsx", { id: "lp-ja" }),
  route("terms", "routes/terms.tsx"),
  route("terms/ja", "routes/terms.tsx", { id: "terms-ja" }),
  route("policy", "routes/policy.tsx"),
  route("policy/ja", "routes/policy.tsx", { id: "policy-ja" }),
  route("tokushoho", "routes/tokushoho.tsx"),
  route("tokushoho/ja", "routes/tokushoho.tsx", { id: "tokushoho-ja" }),
  route("manual/:chapter?", "routes/manual.tsx"),
  route("manual/ja/:chapter?", "routes/manual.tsx", { id: "manual-ja" }),
  route("auth/google", "routes/auth.google.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
  route("auth/logout", "routes/auth.logout.tsx"),
  route("api/auth/unlock", "routes/api.auth.unlock.tsx"),
  route("api/session/me", "routes/api.session.me.tsx"),
  route("settings", "routes/settings.tsx"),
  // Organizations (multi-tenant orgs/projects — gated on isFirestoreAvailable)
  route("login", "routes/login.tsx"),
  route("api/session/select", "routes/api.session.select.tsx"),
  route("api/orgs/list", "routes/api.orgs.list.tsx"),
  route("api/orgs/create", "routes/api.orgs.create.tsx"),
  route("api/orgs/idp", "routes/api.orgs.idp.tsx"),
  route("api/orgs/ai-settings", "routes/api.orgs.ai-settings.tsx"),
  route("api/orgs/vertex-oauth", "routes/api.orgs.vertex-oauth.tsx"),
  route("auth/vertex/start", "routes/auth.vertex.start.tsx"),
  route("auth/vertex/callback", "routes/auth.vertex.callback.tsx"),
  route("api/audit-logs", "routes/api.audit-logs.tsx"),
  route("api/projects/list", "routes/api.projects.list.tsx"),
  route("api/projects/create", "routes/api.projects.create.tsx"),
  route("api/projects/delete", "routes/api.projects.delete.tsx"),
  route("api/projects/update-slug", "routes/api.projects.update-slug.tsx"),
  route("api/members/list", "routes/api.members.list.tsx"),
  route("api/members/add", "routes/api.members.add.tsx"),
  route("api/members/remove", "routes/api.members.remove.tsx"),
  route("api/members/update-role", "routes/api.members.update-role.tsx"),
  route("api/members/ai-budget", "routes/api.members.ai-budget.tsx"),
  route("api/members/invite", "routes/api.members.invite.tsx"),
  route("invite/:token", "routes/invite.$token.tsx"),
  route("admin/enterprise", "routes/admin.enterprise.tsx"),
  route("auth/oidc/start", "routes/auth.oidc.start.tsx"),
  route("auth/oidc/callback", "routes/auth.oidc.callback.tsx"),
  // Unified storage API (mount = "drive" | "project:{id}")
  route("api/storage/read", "routes/api.storage.read.tsx"),
  route("api/storage/write", "routes/api.storage.write.tsx"),
  route("api/storage/delete", "routes/api.storage.delete.tsx"),
  route("api/storage/list", "routes/api.storage.list.tsx"),
  route("api/storage/quota", "routes/api.storage.quota.tsx"),
  route("api/storage/tree", "routes/api.storage.tree.tsx"),
  route("api/storage/rename", "routes/api.storage.rename.tsx"),
  route("api/storage/upload", "routes/api.storage.upload.tsx"),
  route("api/storage/move-between-mounts", "routes/api.storage.move-between-mounts.tsx"),
  route("api/rag/search", "routes/api.rag.search.tsx"),
  route("api/rag/refine", "routes/api.rag.refine.tsx"),
  // API routes
  route("api/drive/files", "routes/api.drive.files.tsx"),
  route("api/drive/tree", "routes/api.drive.tree.tsx"),
  route("api/workflow/execute-node", "routes/api.workflow.execute-node.tsx"),
  route("api/workflow/mcp-proxy", "routes/api.workflow.mcp-proxy.tsx"),
  route("api/workflow/http-fetch", "routes/api.workflow.http-fetch.tsx"),
  route("api/workflow/ai-generate", "routes/api.workflow.ai-generate.tsx"),
  route("api/workflow/ai-prompt", "routes/api.workflow.ai-prompt.tsx"),
  route("api/workflow/history", "routes/api.workflow.history.tsx"),
  route("api/workflow/request-history", "routes/api.workflow.request-history.tsx"),
  route("api/base/ai-generate", "routes/api.base.ai-generate.tsx"),
  route("api/timeline/ai-rewrite", "routes/api.timeline.ai-rewrite.tsx"),
  route("api/chat", "routes/api.chat.tsx"),
  route("api/chat/interactions", "routes/api.chat.interactions.tsx"),
  route("api/chat/compact", "routes/api.chat.compact.tsx"),
  route("api/chat/history", "routes/api.chat.history.tsx"),
  route("api/personal-vertex/balance", "routes/api.personal-vertex.balance.tsx"),
  route("api/personal-vertex/history", "routes/api.personal-vertex.history.tsx"),
  route("api/personal-vertex/connection", "routes/api.personal-vertex.connection.tsx"),
  route("api/settings/mcp-test", "routes/api.settings.mcp-test.tsx"),
  route("api/settings/mcp-oauth-token", "routes/api.settings.mcp-oauth-token.tsx"),
  route("auth/mcp-oauth-callback", "routes/auth.mcp-oauth-callback.tsx"),
  route("api/settings/rag-sync", "routes/api.settings.rag-sync.tsx"),
  route("api/settings/encryption", "routes/api.settings.encryption.tsx"),
  route("api/settings/edit-history", "routes/api.settings.edit-history.tsx"),
  route("api/settings/edit-history-stats", "routes/api.settings.edit-history-stats.tsx"),
  route("api/settings/edit-history-prune", "routes/api.settings.edit-history-prune.tsx"),
  route("api/settings/hubwork-sheets", "routes/api.settings.hubwork-sheets.tsx"),
  route("api/settings/hubwork-provision", "routes/api.settings.hubwork-provision.tsx"),
  route("api/settings/hubwork-migrate", "routes/api.settings.hubwork-migrate.tsx"),
  route("api/settings/external-skills", "routes/api.settings.external-skills.tsx"),
  route("api/okf/gemihub", "routes/api.okf.gemihub.tsx"),
  route("api/hubwork/webpage-review", "routes/api.hubwork.webpage-review.tsx"),
  // Admin workflow endpoint — resolves admin/api/*.yaml under the IDE
  // session's OAuth. The IDE session cookie + same-origin (validateOrigin)
  // are the auth boundary; admin/ being outside the public Hubwork serving
  // layer keeps these workflows off the custom domain but is not by itself
  // an authorization check.
  route("api/admin/accounts", "routes/api.admin.accounts.tsx"),
  route("api/hubwork/admin/*", "routes/api.hubwork.admin.$.tsx"),
  route("api/calendar", "routes/api.calendar.tsx"),
  route("api/gmail", "routes/api.gmail.tsx"),
  route("api/google/picker", "routes/api.google.picker.tsx"),
  route("api/sheets", "routes/api.sheets.tsx"),
  route("api/mcp/tool-call", "routes/api.mcp.tool-call.tsx"),
  route("api/mcp/resource-read", "routes/api.mcp.resource-read.tsx"),
  route("api/search", "routes/api.search.tsx"),
  route("api/embed-check", "routes/api.embed-check.tsx"),
  route("api/sync", "routes/api.sync.tsx"),
  route("api/drive/upload", "routes/api.drive.upload.tsx"),
  route("api/drive/upload-resumable", "routes/api.drive.upload-resumable.tsx"),
  route("api/drive/temp", "routes/api.drive.temp.tsx"),
  // Public (no auth) — temp edit URLs for local editor integration
  route("api/temp-edit/:token/:fileName", "routes/api.temp-edit.$token.$fileName.tsx"),
  // Public (no auth) — serves published Drive files with correct Content-Type
  route("public/file/:fileId/:fileName", "routes/public.file.$fileId.$fileName.tsx"),
  route("api/plugins", "routes/api.plugins.tsx"),
  route("api/plugins/:id", "routes/api.plugins.$id.tsx"),
  route("api/agent-plugins", "routes/api.agent-plugins.tsx"),
  route("api/agent-plugins/:name", "routes/api.agent-plugins.$name.tsx"),
  route("api/obsidian/token", "routes/api.obsidian.token.tsx"),
  // Hubwork routes
  route("hubwork/api/domain", "routes/hubwork.api.domain.tsx"),
  // Hubwork internal endpoints (/__gemihub/ prefix)
  route("__gemihub/auth/login", "routes/hubwork.internal.auth.login.tsx"),
  route("__gemihub/auth/verify/:token", "routes/hubwork.internal.auth.verify.$token.tsx"),
  route("__gemihub/auth/register", "routes/hubwork.internal.auth.register.tsx"),
  route("__gemihub/auth/register/verify/:token", "routes/hubwork.internal.auth.register.verify.$token.tsx"),
  route("__gemihub/auth/logout", "routes/hubwork.internal.auth.logout.tsx"),
  route("__gemihub/auth/me", "routes/hubwork.internal.auth.me.tsx"),
  route("__gemihub/api.js", "routes/hubwork.internal.api-js.tsx"),
  route("__gemihub/api/*", "routes/hubwork.internal.api.$.tsx"),
  route("api/workflow/execute-full", "routes/api.workflow.execute-full.tsx"),
  route("hubwork/api/workflow/scheduled", "routes/hubwork.api.workflow.scheduled.tsx"),
  // Hubwork admin
  // Hubwork Stripe
  route("hubwork/api/stripe/checkout", "routes/hubwork.api.stripe.checkout.tsx"),
  route("hubwork/api/stripe/webhook", "routes/hubwork.api.stripe.webhook.tsx"),
  route("hubwork/api/stripe/portal", "routes/hubwork.api.stripe.portal.tsx"),
  // Hubwork site catch-all (must be last — serves pages from Business GCS projects)
  route("*", "routes/hubwork.site.$.tsx"),
] satisfies RouteConfig;
